### ISSUE TITLE
Runtime error: Error1 in writer, aname = wstar

### ISSUE THREAD

**Issue by jpatiani** [abkenyon/HutsonWeiss2022#1]
Dear @abkenyon,

I'm interested in your work entitled "Using Ensemble Sensitivity Analysis to Identify Storm Characteristics Associated with Tornadogenesis in High-Resolution Simulated Supercells".  
I try to reproduce your work using data that you have uploaded to GitHub (https://github.com/abkenyon/HutsonWeiss2022). However, I still fail to run the control simulation due to no variable found for "wstar" while writing restart output.
My question, is there any modification you made in the cm1 source code? If you modified the code, which part did you modify? 

Thank you very much.
Best regards.

Excerpt from the error log:
leaving restart_prelim
 rain
 sws
 svs
 sps
 srs
 sgs
 sus
 shs
 rain2
 sws2
 svs2
 sps2
 srs2
 sgs2
 sus2
 shs2
 tsk
 rho
 prs
 ua
 va
 wa
 ppi
 tha
 ppx
 qv
 qc
 qr
 qi
 qs
 qg
 nci
 ncs
 ncr
 ncg
 qpten
 qtten
 qvten
 qcten
 ust
 znt
 cd
 ch
 cq
 u1
 v1
 s1
 t1
 u10
 v10
 s10
 xland
 thflux
 qvflux
 psfc
 lu_index
 kpbl2d
 hfx
 qfx
 hpbl
 wspd
 psim
 psih
 gz1oz0
 br
 chs
 chs2
 cqs2
 cpmm
 zol
 mavail
 mol
 rmol
 regime
 lh
 tmn
 flhc
 flqc
 qgh
 ck
 cka
 cda
 ustm
 qsfc
 t2
 q2
 th2
 emiss
 thc
 albd
 gsw
 glw
 chklowq
 capg
 snowc
 fm
 fh
 mznt
 swspd
 wstar
   Error1 in writer, aname = wstar
 NetCDF: Variable not found

**Comment by abkenyon** [comment]
Hello @jpatiani ! No, I did not modify the source CM1 code at all. However, after speaking to several active users of CM1, it turns out this "wstar" error is CM1 version-specific (the aforementioned users cite it in CM1 version 19.10, but I cannot confirm which versions in which it is an issue). I cannot comment on whether this error/bug is in the latest version of CM1, but it does unfortunately require a manual fix in the source code. 

It turns out, both "wstar" and "delta" may be missing from writeout.F and restart.F. The "wstar" and "delta" variables should be listed on the lines below "swspd". It was recommended to me that, in restart.F and writeout.F, you find the line of code defining "swspd", and copy it two more times in the lines below, replacing "swspd" with "wstar" and "delta". 

I hope this helps!

**Comment by jpatiani** [comment]
Hi @abkenyon,
Yes, I use CM1 version 19.10.
I have checked writeout.F and restart.F and seem "wstar" and "delta" write in there.
It turns out that "wstar" and "delta" was missing in writeout_nc.F. 

Thank you for your information and give the idea.
Best regards.


> Hello @jpatiani ! No, I did not modify the source CM1 code at all. However, after speaking to several active users of CM1, it turns out this "wstar" error is CM1 version-specific (the aforementioned users cite it in CM1 version 19.10, but I cannot confirm which versions in which it is an issue). I cannot comment on whether this error/bug is in the latest version of CM1, but it does unfortunately require a manual fix in the source code.
> 
> It turns out, both "wstar" and "delta" may be missing from writeout.F and restart.F. The "wstar" and "delta" variables should be listed on the lines below "swspd". It was recommended to me that, in restart.F and writeout.F, you find the line of code defining "swspd", and copy it two more times in the lines below, replacing "swspd" with "wstar" and "delta".
> 
> I hope this helps!
